#!/bin/bash

uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/psycho_vignette --bootstraps vignettes
uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/psycho_vignette --bootstraps psychometrics

uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/default_issuebench_gemma4sft --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/merged_exports --issuebench-ground-truth resources/input/datasets/issuebench/ground_truth_gemma4sft_fold0_val.parquet
uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/default_issuebench_kimi --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/moonshotai

uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/high_risk_issuebench_kimi --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/moonshotai --issuebench-task-filter resources/output/prompt_ratings/manual_selection.json
uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/high_risk_issuebench_gemma4sft --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/merged_exports --issuebench-ground-truth resources/input/datasets/issuebench/ground_truth_gemma4sft_fold0_val.parquet --issuebench-task-filter resources/output/prompt_ratings/manual_selection.json

uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/no_high_risk_issuebench_kimi --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/moonshotai --issuebench-task-exclude resources/output/prompt_ratings/manual_selection.json
uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/no_high_risk_issuebench_gemma4sft --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/merged_exports --issuebench-ground-truth resources/input/datasets/issuebench/ground_truth_gemma4sft_fold0_val.parquet --issuebench-task-exclude resources/output/prompt_ratings/manual_selection.json

uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/authsys_issuebench_gemma4sft --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan25_auth_en-en-1_0-1-42/IssueBench/judge/merged_exports --issuebench-ground-truth resources/input/datasets/issuebench/ground_truth_gemma4sft_fold0_val.parquet --issuebench-judge-eval-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/merged_exports
uv run run_bootstrap.py --existing-results overwrite --results-dir resources/output/bootstrap_results/authsys_issuebench_kimi --bootstraps issuebench --issuebench-judge-results resources/output/issuebench_judge_jan25_auth_en-en-1_0-1-42/IssueBench/judge/moonshotai --issuebench-judge-eval-results resources/output/issuebench_judge_jan14_en-en-1_0-1-42/IssueBench/judge/moonshotai
